# Generated by Django 2.1.7 on 2019-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, 'warzywa'), (1, 'owoce'), (2, 'zboża'), (3, 'alternatywy nabiału'), (4, 'słodziki'), (5, 'przyprawy'), (6, 'tłuszcze'), (7, 'strączki'), (8, 'orzechy'), (9, 'alkohol')])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=255)),
                ('added', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='api.Category')),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
            ],
        ),
    ]
