# Generated by Django 2.1.7 on 2019-03-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190303_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
    ]
